name: tsan

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tsan_test:
    name: rmf_task tsan
    uses: open-rmf/rmf_ci_templates/.github/workflows/reusable_build.yaml@main
    with:
      dist-matrix: |
          [{"ros_distribution": "rolling",
            "ubuntu_distribution": "noble"}]
      # NOTE: Avoid adding comments in the package lines, this can break some of the called scripts in github actions
      packages: |
        rmf_task
        rmf_task_sequence
      mixin: tsan
